### PR TITLE
Initial commit of Grid Value Resolver.

### PR DESCRIPTION
**Pull request by jamiepollock**
Added in initial Grid Value Resolver. For expected use see the [following gist](https://gist.github.com/jamiepollock/3897e6fa735f0b2a0321).

This PR will need further work to integrate with the main build project proper. Plus some tinkering because of differences in environment.

### CODE REVIEW

**Comment by micklaw** [comment]
Hey Jamie, thanks for spending the time doing this resolver for the framework. It is very much appreciated.

I think this type of Resolver would be best moved in to another project like Common or something along those lines. The idea for the named projects i.e Archetype and Grid, would be to manage the returned types from those assemblies to POCOs via Ditto functionality.

I still think this pull request has its place though i.e getting the HTML in a controller for instance, I just think it would be best moved in to a Common project for Resolvers which aren't used to separate project types to POCOs, but more for getting single types like strings, ints, long, IHtmlString for example, what do you think?

I have actually made a start at mapping the grid to POCOs via TypeConverters and it seems to be working quite well. I'll be firing this up soon, once my internal testing has been completed of course. You should be able to view the source in the dev branch now to see what i am aiming for. I would love to get your feedback.

**Comment by jamiepollock** [comment]
Hi Mick,
Cheers for looking at this PR. Might take me a while to respond to your comments. Had a bit of a head cold the past 4 days and it's thrown me about a bit.

Initial thoughts are (caveat still a bit under the weather so apologies if I miss the point) not sure of a situation where you would want to return anything but IHtmlString/String, etc from the Grid but I agree if the way to go is have a resolver for a grid models then it should live in Our.Umbraco.Ditto.Resolvers.Grid. Perhaps the Grid to HTML resolver should live in there because it all deals with the same stuff?

Would be interested in the reason for a grid model, might give me ideas for the future :)

Thanks,  
Jamie

**Comment by micklaw** [comment]
Hey Jamie,

Yeah keeping it in the Grid project may be an option, my thinking behind moving it to a Common project is to separate the two type of converters. If they were in the same library I was worried it may be confusing which GridResolver to use.

The idea behind creating a strongly typed grid was to put the control in the programmers hands as to how they resolve the types returned from the Grid control values. Having the grid stored in POCOs could lend to someone creating their ow renderer via extension methods, or even use a completely different framework to render the Content i.e foundation or responsivebp. I understand this can be done via the views currently, but I can't say I'm too keen on the dynamic typed nature of the data in the views. I think this could be cleaned up massively with strong types.

**Comment by micklaw** [comment]
I was thinking we could maybe make this other project a Contrib type thing for general Ditto helpers, Common custom type converters and resolvers?

**Comment by jamiepollock** [comment]
I see what you're saying but converting Grid to HtmlString is a fairly specific task.

Also regards strongly typed grids (also not a huge fan of the dynamic html builder implementation) have you seen the work Andy Butland did a while ago on [strongly typed grids](http://web-matters.blogspot.it/2014/11/using-umbraco-mapper-with-umbraco-grids.html)?

**Comment by micklaw** [comment]
Yeah this is a play on that in honesty. The thing I'm not keen on regarding that solution is the potentially massive switch statement in it. Using existing model binding logic in Ditto we can make this process automated via type converters. The solution in this branch injects your type converters on to your row controls so you can decide how to convert objects to strong types via a framework. Makes sense to keep the model binding logic DRY across implementations.

**Comment by jamiepollock** [comment]
Yep, I agree.

**Comment by micklaw** [comment]
Cool, I'm gong to start this Contrib project in this solution I think and merge this stuff from your pull request to that if that's cool? In fact, I might actually put it in the core solution in here?

**Comment by jamiepollock** [comment]
Yep, I'm happy with that. :) Thanks for talking this through with me. I'm starting to get an idea now where you're going with this.

**Comment by micklaw** [comment]
Jamie, sorry, I'm such a div, I was suppose to message you last month about this. I merged your change in, though reformatted the structure of it slightly and included it in the base resolvers project where what I would regard as core resolvers sit.

So thanks again for your help =)

**Pull request closed without merging**
